### ISSUE TITLE
GraphQL query condition documentation

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1048] opened 2019-04-20 13:09 UTC
There should be extensive documentation on how to use conditions for fields while perform GraphQL queries using Keystone API. 
I am no expert in GraphQL. Don't know if following conditions are built in to standard GraphQL or Keystone innovations. I feel they should be documented regardless.

## id field conditions
- *id*_not
- *id*_in
- *id*_not_in

## in conditions
- *<field\>*_in
- *<field\>*_not_in

## equality condition
- *<field\>*_not

### equality with case insensitivity
- *<field\>*_i
- *<field\>*_not_i

## ordering conditions
- *<field\>*_lt
- *<field\>*_lte
- *<field\>*_gt
- *<field\>*_gte

## string condition
- *<field\>*_contains
- *<field\>*_not_contains
- *<field\>*_starts_with
- *<field\>*_not_starts_with
- *<field\>*_ends_with
- *<field\>*_not_ends_with

### string comparison with case insensitivity
- *<field\>*_contains_i
- *<field\>*_not_contains_i
- *<field\>*_starts_with_i
- *<field\>*_not_starts_with_i
- *<field\>*_ends_with_i
- *<field\>*_not_ends_with_i

## Relationship Queries
- *<field\>*_every
- *<field\>*_some
- *<field\>*_none
- *<field\>*_????

## Specific condition
- *<field\>*_is_null
- *<password_field\>*_is_set

not sure if there is **- *<field\>*_is_not_null** condition as well

Please add if I miss anything It may help in documenting them in a PR

**Comment by molomby** [comment] 2019-04-23 00:50
> There should be extensive documentation on how to use conditions for fields while perform GraphQL queries using Keystone API.

Yes indeed :)

> I am no expert in GraphQL. Don't know if following conditions are built in to standard GraphQL or Keystone innovations.

They're not inherent in GraphQL but I wouldn't claim credit for them either. We've taken some inspiration from common GraphQL API patterns and standard like [OpenCRUD](https://github.com/opencrud/opencrud).

The GraphQL filters are all provided by the field types so this might be a dupe of #226.

**Comment by MadeByMike** [comment] 2019-10-21 08:20
This is now documented in many places :) We have the GQL playground of course, and [Intro to GraphQL](https://v5.keystonejs.com/guides/intro-to-graphql) and the [GraphQL philosophy](https://v5.keystonejs.com/quick-start/graphql-philosophy)

**Closed by MadeByMike** 2019-10-21 08:20 UTC
Labels: docs, good first issue
