### ISSUE TITLE
Hide label column in administration UI

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1072] opened 2019-05-01 03:51 UTC
When I have provided a `labelResolver` for a schema item,  it oftentimes mirrors another field.

``` js
{
  labelResolver: x => x.name,
  name: { type: Text, isUnique: true },
  ...
}
```

Is there a way to hide `label` from showing in the administration interface (as both `name` and `label` are equivalent).

**Comment by dcousens** [comment] 2019-05-01 03:53
Possibly resolvable with https://github.com/keystonejs/keystone-5/issues/979

**Comment by MadeByMike** [comment] 2019-10-21 07:44
I'd say a set of default cols is the way to solve this. Closing as dupe of: #979

**Closed by MadeByMike** 2019-10-21 07:44 UTC
Labels: admin-ui, bug, needs-review

**Comment by karmux** [comment] 2019-12-29 14:30
Issue still persists. Setting defaultColumns doesn't hide Label column.

**Comment by gioravered** [comment] 2022-01-16 17:13
Any news about this issue?
