### ISSUE TITLE
Definable workflows

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#312] opened 2018-09-14 00:58 UTC
The ability to define a state machine through which items in a particular list exist.

This was initially being driven by publishing requirements in Vocal (eg. "publishing workflows") but is a common pattern. For example, in Hotel101, visits, bookings and charges all have defined states they can exist in and rules limiting their transition between states. 

Basically like a simple version of [Jira workflows](https://confluence.atlassian.com/adminjiraserver072/working-with-workflows-828787890.html).

These states and transitions would be model for in a way that lets them be:

- Automatically enforced by Keystone (via the hooks framework, presumably: #244)
- Inspectable via the GraphQL endpoint
- Surface and controllable via the Admin UI; so, for example, the values appear nicely (colour coded?) in the list view, maybe items also have buttons for transitioning to the "next" step.

Talking to @timleslie and we reckon this could all be done entirely within the field type framework. The field type can add hooks to the list to enforce it's transitions and we can make meta data available through the GQL endpoint using `gqlAuxQueries`.

**Comment by jesstelford** [comment] 2019-07-04 22:46
KS4 did this with a `dependsOn` option: #1355

**Comment by gautamsi** [comment] 2019-07-05 06:25
`dependsOn` is simplistic approach, the above `StateMachine` field type is also good solution for complex setup with visual effect etc. 
i would prefer to bring dependsOn sooner than the other solution.

**Comment by MadeByMike** [comment] 2019-09-16 06:06
This feels like a duplicate of #1528 - I'd like to close this in favour of #1528. Please re-open if you think there's more here.

**Closed by MadeByMike** 2019-09-16 06:06 UTC
Labels: feature request, fields
