### ISSUE TITLE
POC: packages to be converted to TypeScript

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1460] opened 2019-08-02 09:09 UTC
Tracker for #1373 progress

Overall steps:
1. Convert Front end code first.
      1. Start with admin-ui
      2. Convert Field Types
      3. Convert arch-ui
2. Convert backend code
3. Convert utilities or supporting code like `create-keystone-app` if needed

packages to be converted (not in a priority list)

### Admin Ui
:construction: `admin-ui`  #1454 

### Field Types:

|                status 	|                                field 	            | # 	|
|----------------------:	|-------------------------------------:	            |--:	|
| :white_medium_square: 	| CalendarDay                                      	|   	|
| :white_medium_square: 	| Checkbox                                      	|   	|
| :white_medium_square: 	| CloudinaryImage                                   |   	|
| :white_medium_square: 	| Color                                      	    |   	|
| :white_medium_square: 	| DateTime                                      	|   	|
| :white_medium_square: 	| Decimal                                      	    |   	|
| :white_medium_square: 	| File                                      	    |   	|
| :white_medium_square: 	| Float                                      	    |   	|
| :white_medium_square: 	| Integer                                      	    |   	|
| :white_medium_square: 	| OEmbed                                      	    |   	|
| :white_medium_square: 	| oembed-adapters            |   	|
| :white_medium_square: 	| Password                                      	|   	|
| :white_medium_square: 	| Relationship                                      |   	|
| :white_medium_square: 	| Select                                      	    |   	|
| :white_medium_square: 	| Slug                                      	    |   	|
| :white_medium_square: 	| Text                                      	    |   	|
| :white_medium_square: 	| Unsplash                                      	|   	|
| :white_medium_square: 	| Url                                      	        |   	|
| :white_medium_square: 	| Uuid                                      	    |   	|
|                       	|                                             	    |   	|
| :white_medium_square: 	| field-content                                     |   	|
| :white_medium_square: 	| field-views-loader                                |   	|
| :white_medium_square: 	| fields-auto-increment                             |   	|
| :white_medium_square: 	| fields-datetime-utc                               |   	|
| :white_medium_square: 	| fields-markdown                                   |   	|
| :white_medium_square: 	| fields-mongoid                                    |   	|
| :white_medium_square: 	| fields-wysiwyg-tinymce                      	    |   	|

### Arch UI components

|                status 	|        component      | # 	|
|----------------------:	|-----------------:     |--:	|
| :white_medium_square: 	| alert                 |   	|
| :white_medium_square: 	| badge                 |   	|
| :white_medium_square: 	| button                |   	|
| :white_medium_square: 	| card                  |   	|
| :white_medium_square: 	| color-utils           |   	|
| :white_medium_square: 	| common                |   	|
| :white_medium_square: 	| confirm               |   	|
| :white_medium_square: 	| controls              |   	|
| :white_medium_square: 	| day-picker            |   	|
| :white_medium_square: 	| dialog                |   	|
| :white_medium_square: 	| drawer                |   	|
| :white_medium_square: 	| dropdown              |   	|
| :white_medium_square: 	| example.md            |   	|
| :white_medium_square: 	| fields                |   	|
| :white_medium_square: 	| filters               |   	|
| :white_medium_square: 	| hooks                 |   	|
| :white_medium_square: 	| icons                 |   	|
| :white_medium_square: 	| input                 |   	|
| :white_medium_square: 	| layout                |   	|
| :white_medium_square: 	| loading               |   	|
| :white_medium_square: 	| lozenge               |   	|
| :white_medium_square: 	| modal-utils           |   	|
| :white_medium_square: 	| navbar                |   	|
| :white_medium_square: 	| options               |   	|
| :white_medium_square: 	| pagination            |   	|
| :white_medium_square: 	| pill                  |   	|
| :white_medium_square: 	| popout                |   	|
| :white_medium_square: 	| select                |   	|
| :white_medium_square: 	| theme                 |   	|
| :white_medium_square: 	| tooltip               |   	|
| :white_medium_square: 	| typography            |   	|

**Comment by MadeByMike** [comment] 2019-08-25 23:14
I'm closing this as a duplicate of #1373. Sorry @gautamsi we can save this list for once we have made decisions on that issue.

**Closed by MadeByMike** 2019-08-25 23:14 UTC
Labels: question / idea
