### ISSUE TITLE
Add support for migrations in knex adapter

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#818] opened 2019-03-12 22:36 UTC
At the moment, if you use the `knex` adapter, the database will get dropped every time you connect.

Obviously, this is a long way from ideal. We need to develop a strategy for knex migrations which will support both creation of tables on the initial connect, and then also manage the database as the shape of the schema changes.

**Comment by molomby** [comment] 2019-08-08 01:32
Dupe of #299?

**Comment by MadeByMike** [comment] 2019-10-20 23:54
Yep I'm going to close this as a dupe. I don't think we want to solve for Knex alone

**Closed by MadeByMike** 2019-10-20 23:54 UTC
Labels: knex, needs-review
